apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.workloadIdentity.serviceAccountName }}
  namespace: '{{ .Release.Namespace }}'
  annotations:
    azure.workload.identity/client-id: {{ .Values.workloadIdentity.clientId | quote}}
    azure.workload.identity/tenant-id: {{ .Values.workloadIdentity.tenantId | quote}}