apiVersion: v1
kind: Service
metadata:
  name: {{ include "chart.fullname" . }}-svc
  namespace: '{{ .Release.Namespace }}'
  labels:
    app: {{ include "chart.fullname" . }}
spec:
  ports:
  - name: http
    port: 443
    targetPort: 8080
  - name: metrics
    port: 8081
    targetPort: 8081
  selector:
    app: {{ include "chart.fullname" . }}